<a href="https://colab.research.google.com/github/ahmadr9279/Data-Analytics-course/blob/main/Ahmad_Rabah_3_1_Numpy_class_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

* NumPy Fundamentals
* Basic operations 
* Accessing elements 
* Indexing techniques
* Creating copy and view
* Broadcasting techniques
* Linear Algebra


In [ ]:
# must import numpy to access the library and its functions
# frequently abbreviated as np
import numpy as np 

In [ ]:
#creating an array called a and storing 6 integers in it
#use the np.array() function
a = np.array([1, 2, 3, 4, 5, 6])

print(a)

[1 2 3 4 5 6]


##Attributes of an array

In [ ]:

print(a.ndim) #.ndim returns the number of dimensions (axes) of an array
print(a.shape) #.shape returns a tuple showing the size of the array in each dimension
print(a.size) #.size returns the total number of elements in the array (dimXshape)
print(a.dtype) #.dtype returns data type of elements in the array


1
(6,)
6
int64


In [ ]:
#These are the exact same code, but the second one has line breaks to show the array better
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


b = np.array(
    [[1, 2, 3, 4], 
     [5, 6, 7, 8], 
     [9, 10, 11, 12]])

In [ ]:
print(b.ndim) #.ndim returns the number of dimensions (axes) of an array
print(b.shape) #.shape returns a tuple showing the size of the array in each dimension
print(b.size) #.size returns the total number of elements in the array
print(b.dtype)

2
(3, 4)
12
int64


## Arrays can also include characters

In [ ]:
np_city = np.array(['NYC', 'LA', 'Miami', 'Houston'])
np_city_with_state = np.array([['NYC', 'LA', 'Miami', 'Houston'], ['NY', 'CA', 'FL','TX']])

print(np_city)
print('\n')
print(np_city_with_state)

['NYC' 'LA' 'Miami' 'Houston']


[['NYC' 'LA' 'Miami' 'Houston']
 ['NY' 'CA' 'FL' 'TX']]


In [ ]:
#look at number of dimensions
print(np_city.ndim)
print(np_city_with_state.ndim)

1
2


In [ ]:
#look at shape
print(np_city.shape)
print(np_city_with_state.shape)

(4,)
(2, 4)


In [ ]:
#look at size
print(np_city.size)
print(np_city_with_state.size)

4
8


In [ ]:
#look at data type
print(np_city.dtype)
print(np_city_with_state.dtype) 
#strings with max of 7 characters

<U7
<U7


#YOUR TURN 1

* Create an array with one row and 10 numbers

In [ ]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10]


* Print the dimension, shape, size and data type for your array.

In [ ]:
print(my_array.ndim)
print(my_array.shape)
print(my_array.size)
print(my_array.dtype)

1
(10,)
10
int64


* Create an array wtih two rows and three words in each row.


In [ ]:
my_2d = np.array([['Hello','There', 'How'],['Are','You','Today']])

* Print the dimension, shape, size and data type for your array.

In [ ]:
print(my_2d.ndim)
print(my_2d.shape)
print(my_2d.size)
print(my_2d.dtype)


2
(2, 3)
6
<U5


##Basic operations on arrays



#### Addition
NumPy uses the indices of the elements in each array to carry out basic operations. In this case, where we are looking at a dataset of four cyclists during two trials, vector addition of the arrays gives the required output.


In [ ]:
#create two listss with the cyclist distances

trial_1 = [10,15,17,26] 
trial_2 = [12,11,21,24] 

#convert lists to numpy arrays

np_trial_1 = np.array(trial_1)
np_trial_2 = np.array(trial_2)

In [ ]:
#use array addition to add the elements of each array

np_trial_1 + np_trial_2


array([22, 26, 38, 50])

#YOUR TURN 2

Use the provided arrays to perform simple array operations.

In [ ]:
#Provided arrays
a = np.array([6,11,12,14]) 
b = np.array([24,15,7,19])

Array a plus array b

In [ ]:
print(a+b)

[30 26 19 33]


Array a minus array b
and array b minus array a

In [ ]:
print(a-b)
print(b-a)

[-18  -4   5  -5]
[18  4 -5  5]


Array a mulitplied by array b

In [ ]:
print(a*b)

[144 165  84 266]


What do you notice about how these operations work? How does this differ from operations with python lists?

You can not use math operations like addition and subtraction on Python lists, however, you can with arrays.

##Accessing elements using indexing

You can access an entire row of an array by referencing its axis index. The index starts at 0

> Indented block




In [ ]:
cyclist_trials = np.array([[10,15,17,26], [12,11,21,24]]) #creates 2-d array from cyclist trial data

cyclist_trials

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [ ]:
#access first row
first_trial = cyclist_trials[0]

#access second row
second_trial = cyclist_trials[1]

In [ ]:
first_trial

array([10, 15, 17, 26])

In [ ]:
second_trial

array([12, 11, 21, 24])

In [ ]:
#selecting individual elements using index on two axes

print(cyclist_trials[0][0]) # first row, first element
print(cyclist_trials[1][3]) # second row, fourth element

10
24


In [ ]:
#select all rows of an array, first element of each row using :

cyclist_trials[:,0]

array([10, 12])

In [ ]:
#you can also use the where() function to find the index position of a value

np.where(cyclist_trials == 17)

(array([0]), array([2]))

#YOUR TURN 3

Create a new array with of integers with three rows of four elements each. Use the index to do the following:

In [ ]:
third_array = np.array([[7,9,15,21],[23,45,63,74],[16,15,29,12]])
print(third_array)

[[ 7  9 15 21]
 [23 45 63 74]
 [16 15 29 12]]


* Access the first row of your array.


In [ ]:
print(third_array[0,:])

[ 7  9 15 21]


* Access the third row of your array.

In [ ]:
print(third_array[2,:])

[16 15 29 12]


* Access the second row, third element of your array.

In [ ]:
print(third_array[1,2])

63


* Access the fourth element of each row of your array.

In [ ]:
print(third_array[:,3])

[21 74 12]


##Indexing with boolean arrays

In [ ]:
test_scores = np.array([[83,71,57,63], [54,68,81,45]])

test_scores

array([[83, 71, 57, 63],
       [54, 68, 81, 45]])

In [ ]:
passing_score = test_scores > 60

In [ ]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [ ]:
test_scores[passing_score]

array([83, 71, 63, 68, 81])

##Copies and views

When working with arrays, you can assign an array as the same values, view a copy or make a copy. 

Simple asignment does not create a copy

In [ ]:
## new array with boroughs of nyc

nyc_borough = np.array(['manhattan', 'bronx', 'brooklyn', 'staten island', 'queens'])
           
new_nyc_borough = nyc_borough # no new object is created
new_nyc_borough is nyc_borough  # these are now two names for the same ndarray object

True

In [ ]:
#if you change one of them you change both

nyc_borough[4] = 'central park'

print(nyc_borough)
print(new_nyc_borough)

['manhattan' 'bronx' 'brooklyn' 'staten island' 'central park']
['manhattan' 'bronx' 'brooklyn' 'staten island' 'central park']


In [ ]:
#reset the array to original
nyc_borough = np.array(['manhattan', 'bronx', 'brooklyn', 'staten island', 'queens'])


.view() creates a "shallow copy," or a new array object with the same data. Making changes to either the original or new will also make changes in the other one.


In [ ]:
view_of_nyc_borough = nyc_borough.view() #use .view() function to create a new array

view_of_nyc_borough


array(['manhattan', 'bronx', 'brooklyn', 'staten island', 'queens'],
      dtype='<U13')

In [ ]:
#when you change the view, you change the original

view_of_nyc_borough[4] = 'central park'

print(nyc_borough) #print original
print(view_of_nyc_borough) #print view


['manhattan' 'bronx' 'brooklyn' 'staten island' 'central park']
['manhattan' 'bronx' 'brooklyn' 'staten island' 'central park']


In [ ]:
#or when you change the original you change the view

nyc_borough[3] = 'si'

print(nyc_borough) #print original
print(view_of_nyc_borough) #print view

['manhattan' 'bronx' 'brooklyn' 'si' 'central park']
['manhattan' 'bronx' 'brooklyn' 'si' 'central park']


In [ ]:
#reset array to the original 

nyc_borough = np.array(['manhattan', 'bronx', 'brooklyn', 'staten island', 'queens'])


.copy() creates a "deep copy" or a whole new copy of the data and changes to one copy do not affect the other

In [ ]:
#create a copy

copy_of_nyc_borough = nyc_borough.copy() 


In [ ]:
#change the copy

copy_of_nyc_borough[4] = 'central park'

In [ ]:
#the copy has changed but the original remains the same

print(nyc_borough) #print original
print(copy_of_nyc_borough) #print copy

['manhattan' 'bronx' 'brooklyn' 'staten island' 'queens']
['manhattan' 'bronx' 'brooklyn' 'staten island' 'central park']


#YOUR TURN 4

Create a new array with five text values of your favorite colors. 

In [ ]:
my_colors =np.array(['blue','green','purple','yellow','orange'])

* Make a new variable and assign it the value of your original array (simple assignment). Change the second value of the array using the new name. Print the old and new names of the array and see what happened.


In [136]:
new_colors = my_colors
new_colors is my_colors

True

In [137]:
new_colors[1] = 'velvet'
print(new_colors)
print(my_colors)

['blue' 'velvet' 'purple' 'yellow' 'orange']
['blue' 'velvet' 'purple' 'yellow' 'orange']


* Create a view of the original array. Change the second value of the array using the view. Print the old and new names of the array and see what happened.

In [143]:
view_colors = my_colors.view()
my_colors[1] = 'green'
print(my_colors)
print(view_colors)

['blue' 'green' 'purple' 'yellow' 'orange']
['blue' 'green' 'purple' 'yellow' 'orange']


* Create a copy of the original array. Change the second value of the array using the view. Print the old and new names of the array and see what happened.


In [141]:
copy_colors = my_colors.copy()
my_colors[1] = 'velvet'
copy_colors[1] = 'magenta'
print(my_colors)
print(copy_colors)

['blue' 'velvet' 'purple' 'yellow' 'orange']
['blue' 'magent' 'purple' 'yellow' 'orange']


#Universal functions

NumPy provides useful mathematical functions called Universal Functions. These functions operate element-wise on an array, producing another array as output. 

In [148]:
#create some new arrays to work with our functions

a = np.array([2,4,9,16,25])
b = np.array([1.3, 2.5, 3.7, 7.19, -1.1, -2.8])

In [149]:
#Find the square root of each element in the array

np.sqrt(a)


array([1.41421356, 2.        , 3.        , 4.        , 5.        ])

In [150]:
#find the floor (largest integer) for each element in the array

np.floor(b)

array([ 1.,  2.,  3.,  7., -2., -3.])

In [151]:
#you can even do trig!

print(np.cos(0))
print(np.sin(1))


1.0
0.8414709848078965


In [152]:
from numpy import pi 

np.sin(pi/2)

1.0

#Broadcasting

NumPy uses broadcasting to carry out arithmetic operations between arrays of different shapes. In this method, NumPy automatically broadcasts the smaller array over the larger array. 

In [153]:
#create two arrays of the same size

array_a = np.array([2,3,5,8])
array_b = np.array([.3,.3,.3,.3])

In [154]:
#multiply the arrays. because they are the same size, this is element-wise operation

array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [155]:
#create a scalar value (not an array)

scalar_c = .3

In [156]:
#multiply array_a by the scalar 
#the scalar will be 'broadcast' across the array

array_a * scalar_c

array([0.6, 0.9, 1.5, 2.4])

#Linear algebra

####Transpose

NumPy can carry out linear algebraic functions as well. The “transpose()” function can help you interchange rows as columns, and vice-versa.


In [157]:
test_scores = np.array([[83,71,57,63], [54,68,81,45]])

test_scores

array([[83, 71, 57, 63],
       [54, 68, 81, 45]])

In [158]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])